version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "S3DSBucketName=\"kraocustomerdata\" IdentityCenterInstanceArn=\"arn:aws:sso:::instance/ssoins-7223dc7ba78cff36\""
image_repositories = []
