version = 0.1
[default.deploy.parameters]
stack_name = "ihotrskrydu"
resolve_s3 = true
s3_prefix = "ihotrskrydu"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "IdentityCenterInstanceArn=\"arn:aws:sso:::instance/ssoins-72232d339c320c7c\" SlackSecretArn=\"arn:aws:secretsmanager:us-east-1:428325390718:secret:QBusiness-Slack-test-tScPdG\" YOURSLACKTEAMID=\"T062EARNCRF\""
image_repositories = []
