Transform: AWS::Serverless-2016-10-31
Description: Q Business Slack SAM sample pattern (uksb-y0x1nlspob) (tag:qbusiness-slack-sam)
Parameters:
  IdentityCenterInstanceArn:
    Type: String
    Description: Enter the ARN of the Amazon Q Business Identity Center instance.
  SlackSecretArn:
    Type: String
    Description: Enter the ARN of the AWS Secrets manager secret containing your Slack credentials.
  YOURSLACKTEAMID:
    Type: String
    Description: Enter your team ID from the Slack workspace you want to associate with Amazon Q Business.
  

Resources:
  QBusinessApplication:
    Type: AWS::QBusiness::Application
    Properties:
      DisplayName: !Sub MyQBusinessApp-${AWS::StackName}
      Description: Amazon Q Business Application
      IdentityCenterInstanceArn: !Ref IdentityCenterInstanceArn
  QBusinessWebExperienceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - application.qbusiness.amazonaws.com
            Action:
              - sts:AssumeRole
              - sts:SetContext
      Description: IAM role for Q Business Web Experience
      RoleName: !Sub QBusinessWebExperienceRole-${AWS::StackName}
      Policies:
        - PolicyName:  WebExperiencePolicyIdC
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: QBusinessConversationPermission
                Effect: Allow
                Action:
                  - qbusiness:Chat
                  - qbusiness:ChatSync
                  - qbusiness:ListMessages
                  - qbusiness:ListConversations
                  - qbusiness:DeleteConversation
                  - qbusiness:PutFeedback
                  - qbusiness:GetWebExperience
                  - qbusiness:GetApplication
                  - qbusiness:ListPlugins
                  - qbusiness:GetChatControlsConfiguration
                Resource:
                  Fn::Sub:
                    - 'arn:aws:qbusiness:${AWS::Region}:${AWS::AccountId}:application/${ApplicationId}'
                    - ApplicationId: !GetAtt QBusinessApplication.ApplicationId
              - Sid: QBusinessKMSDecryptPermissions
                Effect: Allow
                Action: kms:Decrypt
                Resource:
                  Fn::Sub: 'arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/*'
                Condition:
                  StringLike:
                    kms:ViaService:
                      Fn::Sub: 'qbusiness.${AWS::Region}.amazonaws.com'
              - Sid: QBusinessSetContextPermissions
                Effect: Allow
                Action: sts:SetContext
                Resource: 'arn:aws:sts::*:self'
                Condition:
                  StringLike:
                    aws:CalledViaLast: 'qbusiness.amazonaws.com'

  # Create a QBusiness Web Experience
  QBusinessWebExperience:
    Type: 'AWS::QBusiness::WebExperience'
    DependsOn:
      - QBusinessApplication
    Properties:
      ApplicationId: !Ref QBusinessApplication
      RoleArn: !GetAtt QBusinessWebExperienceRole.Arn
  
  QBusinessIndex:
    DependsOn:
      - QBusinessApplication
      - QBusinessWebExperience
    Type: AWS::QBusiness::Index
    Properties:
      DisplayName: MyQBusinessIndex
      Description: My Amazon Q Business Index
      ApplicationId: !Ref QBusinessApplication
  
  QBusinessRetriever:
    Type: AWS::QBusiness::Retriever
    Properties:
      ApplicationId: !Ref QBusinessApplication
      Configuration: 
        NativeIndexConfiguration:
          IndexId: !GetAtt QBusinessIndex.IndexId
      DisplayName: MyQBusinessRetriever
      Type: 'NATIVE_INDEX'

  SlackDataSourceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service:
                - qbusiness.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: SlackDataSourcePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - qbusiness:BatchPutDocument
                  - qbusiness:BatchDeleteDocument
                Resource:
                  - !Sub 'arn:aws:qbusiness:${AWS::Region}:${AWS::AccountId}:application/${QBusinessApplication.ApplicationId}/index/*'
              - Effect: Allow
                Action:
                  - qbusiness:PutGroup
                  - qbusiness:CreateUser
                  - qbusiness:DeleteGroup
                  - qbusiness:UpdateUser
                  - qbusiness:ListGroups
                Resource:
                  - !Sub 'arn:aws:qbusiness:${AWS::Region}:${AWS::AccountId}:application/${QBusinessApplication.ApplicationId}'
                  - !Sub 'arn:aws:qbusiness:${AWS::Region}:${AWS::AccountId}:application/${QBusinessApplication.ApplicationId}/index/*'
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Ref SlackSecretArn

  SlackDataSource:
    DependsOn:
      - QBusinessApplication
      - QBusinessIndex
    Type: AWS::QBusiness::DataSource
    Properties:
      ApplicationId: !Ref QBusinessApplication
      DisplayName: MySlackDataSource
      Description: Slack Data Source for Amazon Q Business
      RoleArn: !GetAtt SlackDataSourceRole.Arn
      IndexId: !GetAtt QBusinessIndex.IndexId
      Configuration:         
        type: SLACK
        syncMode: FULL_CRAWL
        secretArn: !Ref SlackSecretArn
        enableIdentityCrawler: true
        connectionConfiguration:
          repositoryEndpointMetadata:
            teamId: !Ref YOURSLACKTEAMID
        repositoryConfigurations:
          All:
            fieldMappings:
              - indexFieldName: message_id
                indexFieldType: STRING
                dataSourceFieldName: id
                dateFieldFormat: yyyy-MM-dd'T'HH:mm:ss'Z'
        additionalProperties:
          enableDeletionProtection": false
  DataSourceSyncLambda:
    Type: AWS::Serverless::Function
    DependsOn:
      - QBusinessApplication
      - SlackDataSource
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: DataSourceSyncLambda
      CodeUri: src/dataSourceSync/
      Handler: dataSourceSyncLambda.lambda_handler
      Runtime: python3.12
      MemorySize: 1024
      Timeout: 900
      Tracing: Active
      Policies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: '*'
          - Effect: Allow
            Action:
              - qbusiness:StartDataSourceSyncJob
              - qbusiness:StopDataSourceSyncJob
            Resource:
              - !Sub arn:aws:qbusiness:${AWS::Region}:${AWS::AccountId}:application/${QBusinessApplication}
              - !Sub arn:aws:qbusiness:${AWS::Region}:${AWS::AccountId}:application/${QBusinessApplication}/*
      Environment:
        Variables:
          INDEX_ID: !GetAtt QBusinessIndex.IndexId
          DS_ID: !GetAtt SlackDataSource.DataSourceId
          APP_ID: !GetAtt QBusinessApplication.ApplicationId
  DataSourceSync:
    Type: Custom::DataSourceSync
    DependsOn:
      - QBusinessIndex
      - DataSourceSyncLambda
    Properties:
      ServiceToken: !GetAtt DataSourceSyncLambda.Arn
Outputs:
  QBusinessApplicationId:
    Description: Amazon Q Business Application ID
    Value: !Ref QBusinessApplication
  SlackDataSourceId:
    Description: Slack Data Source ID
    Value: !Ref SlackDataSource