version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "ModelId=\"anthropic.claude-instant-v1\" S3DSBucketName=\"kraocustomerdata\" KendraEdition=\"DEVELOPER_EDITION\""
image_repositories = []
